Repository aws2302/abschlussprojekt, pull requests merged in 2024-01, with the labels that each got.

#2 Added Dockerfile (frontend)
  README.md
  docker/Dockerfile
  git.md
Labels: enhancement

#4 added: todo & ideen list
  ansible/todo.md
Labels: documentation

#7 Dokumentation
  docker/Dockerfile
  docker/README.md
Labels: documentation, Docker

#12 FrontEnd/DB-Repo-URL in README aktualisiert
  README.md
Labels: documentation
